name: Build static site and deploy with ssh

on:
  push:
    branches:
      - doodle

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          submodules: true
          lfs: true

      - name: Add SSH key
        uses: shimataro/ssh-key-action@87a8f067114a8ce263df83e9ed5c849953548bc3  # v2.8.1
        with:
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Build and deploy on the host
        run: |
          export DOCKER_HOST=${{ secrets.DOCKER_HOST }}
          export PORT=${{ env.PORT }}
          docker compose --file docker-compose.yml up --detach --build
